# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Example:
# Input:
# s = "abcd"
# t = "abcde"

# Output:
# e

# Explanation:
# 'e' is the letter that was added.


def findTheDifference(s, t):
  """
  :type s: str
  :type t: str
  :rtype: str
  """
  dict = {}
  for letter in t:
    dict[letter] = dict.get(letter, 0) + 1

  for letter in s:
    if letter in dict.keys():
      if dict[letter] == 1:
        del dict[letter]
      else:
        dict[letter] -= 1

  for letter in dict.keys():
    return letter

s = "abcdefg"
t = "bfcazgde"

print(findTheDifference(s, t))